name: Type Checks, Published Types

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '14 5 * * 1'

permissions:
  contents: read

jobs:
  type-check:
    uses: voxpelli/ghatemplates/.github/workflows/type-check.yml@main
    with:
      ts-versions: ${{ github.event.schedule && 'next' || '4.5,4.8,5.1,5.5,5.6,5.7,next' }}
      # ts-versions: 'next'
      ts-libs: 'es2020;esnext'
      ts-working-directory: 'test-published-types'
